// ============================================================
// data.js — FONTE ÚNICA de dados do Hub Matchday 4ComM
// Atualizado em 06/08/2026 a partir de:
//   - Radar_de_Jogos_4ComM.xlsx aba 03 ELENCO (carteira de gestores
//     preenchida pelo Head de Conteúdo em 27/07 — FONTE OFICIAL)
//   - hub_data.json (diagnóstico WhatsApp 06/08 — trilhas e fila)
// Próximo passo do backlog: gerar este arquivo do Google Sheets.
// Formato atletas: [nome, categoria/tier, clube, gestor, trilha(designer), marca, obs, apelido, equipes[]]
// Formato jogos:   [competição, adversário, mando, data, hora, local, fonte, probabilidade, gatilhoA(0/1)]
// ============================================================
window.__DATA = {
"gerado": "06/08/2026 · carteira oficial 27/07 (Head de Conteúdo)",

"atletas": [
// ---- Profissional ----
["Gabigol", "Pro T2A", "Santos", "Junior Pedroso", "Felipe Salles", "—", "emprestado pelo Cruzeiro", "Gabriel Barbosa", []],
["Pablo Maia", "Pro T2A", "São Paulo", "Felipe Guimarães", "Felipe Salles", "Adidas", "", "", []],
["Thayllon", "Pro T3A", "Avaí", "Fran", "Felipe Salles", "SPK (parceiro)", "logo 4ComM + SPK, SPK primeiro não — 4ComM primeiro", "Thayllon Roberth", []],
["Moisés", "Pro T3A", "CSKA Moscou", "Felipe Guimarães", "Felipe Salles", "—", "fuso Rússia: entregar cedo", "", []],
["Peglow", "Pro T3A", "DC United", "Papito", "Edu/Leo", "—", "horário BRA + EUA", "João Peglow", []],
["Giovanni", "Pro T4A", "Ballkani", "Papito", "Felipe Salles", "—", "sem patrocinador fixo", "", []],
["Ryan Nascimento", "Pro T4A", "Bahia", "Roberto", "(definir)", "Puma", "marcar Puma Salvador Shopping em ação de loja · vice-artilheiro do Baiano 2026", "Ryan", ["Bahia Sub-20"]],
["Patrick de Lucca", "Pro T4A", "CRB", "Henrique", "(definir)", "—", "", "De Lucca", []],
["Felipe Oliveira", "Pro T4B", "São Paulo", "Henrique", "(definir)", "—", "", "", []],
["Kayk Alboes", "Pro T5A", "Linense", "Roberto", "(definir)", "—", "clube corrigido p/ Linense (Head de Conteúdo, 25/07)", "Kayk", []],
["Felipe Amaral", "Pro T3B", "América-MG", "Papito", "(definir)", "—", "", "Amaral", []],
["Kauê Canela", "Pro T5A", "Fortaleza", "Henrique", "(definir)", "—", "⚠ doc do fluxo diz Botafogo-PB — confirmar clube", "Kaue Canela", []],
["Hwaskar", "Pro T5B", "São Bernardo", "Henrique", "—", "—", "OPT-OUT total — não fazer artes (23/07)", "Hwaskar Fagundes", []],
["Thalisson", "Pro T3B", "Ceará", "Felipe Guimarães", "(definir)", "—", "NÃO usa IA — 'abomina'", "", []],
["Antony", "Pro", "Real Betis", "Papito", "(definir)", "—", "", "", []],
["Lucas Moura", "Pro", "São Paulo", "Junior Pedroso", "(definir)", "—", "", "", []],
["Ferreira", "Pro", "São Paulo", "Felipe Guimarães", "(definir)", "—", "", "Ferreirinha", []],
["Fabinho", "Pro", "Coritiba", "Junior Pedroso", "(definir)", "—", "", "", []],
["Palmberg", "Pro", "Real Murcia", "Luis Felipe", "(definir)", "—", "", "João Palmberg", []],
["Guilherme Torres", "Pro", "Al Sadd", "Junior Pedroso", "(definir)", "—", "baixo interesse em ativação de mídia (jul/2026)", "", []],
["Nathan Mendes", "Pro", "EC Vitória", "Henrique", "(definir)", "—", "lesionado — fora da temporada 2026; não cobrar jogo", "Nathan", []],
["Gabriel Alves", "Pro", "Brooklyn FC", "Felipe Guimarães", "(definir)", "—", "", "", []],
["Dija", "Pro", "XV de Piracicaba", "Luis Felipe", "(definir)", "—", "clube confirmado no doc do fluxo (XV, não XI)", "Diego Kauan", []],
["Richard Candido", "Pro", "Internacional", "Junior Pedroso", "(definir)", "—", "em negociação — conteúdo em modo incógnita, não cobrar jogo", "Richard", []],
["Laruccia", "Pro", "Portuguesa", "Luis Felipe", "(definir)", "—", "AUXILIAR TÉCNICO (não treinador — corrigido 27/07); não dá coletiva; racional diferente", "Raphael Laruccia", []],
// ---- Base ----
["Luca Canela", "Base Sub-15", "Athletico-PR", "Henrique", "Gui", "Puma", "fase artilheira — 20 participações em gol nos últimos 20 jogos", "Luca", []],
["Gustavo Passos", "Base Sub-17", "Athletico-PR", "Henrique", "Gui", "—", "", "", []],
["Karlos Samuel", "Base Sub-20", "Avaí", "Henrique", "Gui", "—", "", "Karlos", ["Avaí Sub-20"]],
["Thiaguinho", "Base Sub-20", "Fortaleza", "Henrique", "Gui", "—", "posição: MEIA (corrigido 27/07) · artilheiro do Cearense Sub-20 · emprestado", "", ["Fortaleza Sub-20"]],
["Lorenzo Dracena", "Base Sub-15", "Palmeiras", "Thiago Xavier", "Cauã", "RD (parceiro)", "logo RD sempre", "Lorenzo", ["Palmeiras Sub-15"]],
["Enrico", "Base Sub-14", "Palmeiras", "Thiago Xavier", "Cauã", "Puma", "IA só com aprovação da mãe · ⚠ ELENCO 27/07 diz Sem marca — confirmar", "", ["Palmeiras Sub-14"]],
["Luigi Dracena", "Base Sub-12", "Palmeiras", "Thiago Xavier", "Cauã", "RD (parceiro)", "", "Luigi", []],
["Felipe Brenelli", "Base Sub-15", "Guarani", "Thiago Xavier", "Cauã", "—", "", "Brenelli", ["Guarani Sub-15"]],
["Rafa Martinez", "Base Sub-14", "São Paulo", "Thiago Xavier", "Cauã", "Adidas", "", "Martinez", ["São Paulo Sub-14"]],
["Ryan Ridek", "Base Sub-14", "São Paulo", "Thiago Xavier", "Cauã", "Nike", "", "Ridek", ["São Paulo Sub-14"]],
["Aguirra", "Base Sub-17", "Corinthians", "Thiago Xavier", "Cauã", "—", "NÃO ASSINOU — sem logo 4ComM · não consta no ELENCO do radar — confirmar situação", "", []],
["Leonan", "Base Sub-17", "São Paulo", "Thiago Xavier", "Cauã", "—", "", "", []],
["Matheus Bittencourt", "Base Sub-15", "Referência", "Fran", "Felipe Salles", "Adidas", "SEM IA NO ROSTO — pai aprova (critério: clean) · ⚠ ELENCO diz Sem marca — confirmar", "Bitencourt", ["Referência Sub-15"]],
["Tiago Barros", "Base Sub-17", "Santos", "Fran", "Hyzzi", "—", "", "", ["Santos Sub-17"]],
["Luiz Gusttavo", "Base Sub-17", "Santos", "Fran", "Hyzzi", "—", "2 gols e 1 assistência em 25/07, primeiros pelo Santos", "Luiz Gustavo", ["Santos Sub-17", "Santos Sub-20"]],
["Diogo Oliveira", "Base Sub-15", "Vitória SC", "Fran", "Hyzzi", "Puma", "verificar se houve mudança para o Paris FC", "Dioguinho", []],
["Luiz Felipe", "Base Sub-15", "Juventude", "Fran", "Hyzzi", "—", "assinatura/anúncio pendentes desde 17/07", "Urso", ["Juventude Sub-15"]],
["Pietro Galli", "Base Sub-15", "Cruzeiro", "Papito", "Hyzzi", "—", "", "Pietro", ["Cruzeiro Sub-15"]],
["Rafinha Leonel", "Base Sub-20", "Santo André", "Papito", "Hyzzi", "—", "", "Rafinha", ["Santo André Sub-20"]],
["Rosenthal", "Base Sub-17", "Ibrachina", "Papito", "Hyzzi", "—", "contrato de representação assinado em 27/05/2026", "Felipe Rosenthal", ["Ibrachina Sub-17"]],
["João Toscano", "Base Sub-17", "São Paulo", "Fabio", "Gui", "Puma", "", "Toscano", ["São Paulo Sub-17"]],
["Arthur Diniz", "Base Sub-17", "RB Bragantino", "Fabio", "Letícia*", "Adidas", "⚠ ERRO RECORRENTE: já saiu arte com Puma — a marca é ADIDAS · Seleção Sub-16 · chuteira: modelo NOVO da Adidas", "Diniz", ["RB Bragantino Sub-17"]],
["Arthur Henrique", "Base Sub-15", "São Paulo", "Fabio", "Letícia*", "Adidas", "", "Thuy", ["São Paulo Sub-15"]],
["Diego Fidelis", "Base Sub-15", "São Paulo", "Fabio", "Gui", "Adidas", "", "Dieguinho", ["São Paulo Sub-15"]],
["Gustavo Defante", "Base Sub-17", "Referência", "Fabio", "Gui", "—", "", "Defante", ["Referência Sub-17"]],
["Fellipe Lima", "Base Sub-15", "Água Santa", "Luis Felipe", "Gui", "—", "", "", ["Água Santa Sub-15"]],
["Pedro Tizon", "Base Sub-13", "São Paulo", "Cristiano", "Cauã", "—", "", "Tizon", ["São Paulo Sub-13"]],
["Jean Louis", "Base Sub-19", "Paris FC", "Ivanildo", "(definir)", "—", "primeiro contrato profissional com o Paris FC (jun/2026)", "", []],
["Arthur Gustavo", "Base", "São Paulo", "Cristiano", "(definir)", "—", "", "Arthurzinho", []],
["Cauã Rodrigues", "Base", "Santos", "Fran", "(definir)", "—", "compliance: só usar envelope 4ComM após assinatura com o clube · não confundir com o designer Cauã", "Cauã", ["Santos Sub-17"]],
["Frediani", "Base", "Palmeiras", "Cristiano", "(definir)", "—", "", "", []],
["Guilherme Giehl", "Base", "RB Bragantino", "Thiago Xavier", "(definir)", "—", "emprestado · recusou post promocional com números", "Giehl", []],
["Jhonatan Almeida", "Base", "Internacional", "Luis Felipe", "(definir)", "—", "", "Jhonatan", []],
["Luiz Henrique", "Base", "Real Murcia", "Henrique", "(definir)", "—", "", "Luizinho", []],
["Pedro Gomes", "Base", "Referência", "Henrique", "(definir)", "—", "", "Pedrinho", []],
["Francisco Guimarães", "Base", "Goiás", "Felipe Guimarães", "(definir)", "—", "", "Francisco", []]
],

"gestores": ["Cristiano", "Fabio", "Felipe Guimarães", "Fran", "Henrique", "Ivanildo", "Junior Pedroso", "Luis Felipe", "Papito", "Roberto", "Thiago Xavier", "Outro / marketing"],

"designers": ["Felipe Salles", "Edu/Leo", "Gui", "Cauã", "Hyzzi", "Letícia", "Matheus (plantão)"],

"fila": [
["qui 06/08 15:00", "Gustavo Passos", "BH Cup · Grêmio (C)", "Base", "Alta", "Gui", "Na fila", "mesmo jogo do Luca"],
["qui 06/08 15:00", "Luca Canela", "BH Cup · Grêmio (C)", "Base", "Alta", "Gui", "Na fila", "mesmo jogo do Passos"],
["qui 07/08 15:00", "Luiz Gusttavo", "Paulistão Sub-20 · São Bento (C)", "Base", "Média", "Hyzzi", "Radar", "produzir só D-2 · mando corrigido: casa (CT Rei Pelé)"],
["qui 07/08 20:30", "Thalisson", "Série B · Ponte Preta (C)", "Base", "Alta", "(definir)", "Na fila", "NÃO usa IA"],
["sex 08/08 14:30", "Moisés", "Camp. Russo · FK Rostov (F)", "Especial · A", "Alta", "Felipe Salles", "Em produção", "entregar 5ª à noite — fuso"],
["sáb 08/08 08:00", "Pietro Galli", "Mineiro Sub-15 · Betim (C)", "Base", "Alta", "Hyzzi", "Na fila", ""],
["sáb 08/08 09:00", "Fellipe Lima", "Paulistão Sub-15 · EC S. Bernardo (C)", "Base", "Alta", "Gui", "Na fila", ""],
["sáb 08/08 09:00", "Felipe Brenelli", "Paulistão Sub-15 · São Bernardo FC (C)", "Base", "Alta", "Cauã", "Na fila", ""],
["sáb 08/08 09:00", "Lorenzo Dracena", "Paulistão Sub-15 · Guarulhense (C)", "Base", "Alta", "Cauã", "Na fila", "logo RD sempre"],
["sáb 08/08 09:00", "Diego Fidelis", "Paulistão Sub-15 · São Bento (C)", "Base", "Alta", "Gui", "Na fila", "mesmo jogo do Thuy"],
["sáb 08/08 09:00", "Arthur Henrique", "Paulistão Sub-15 · São Bento (C)", "Base", "Alta", "Letícia*", "Na fila", "mesmo jogo do Dieguinho"],
["sáb 08/08 09:00", "Matheus Bittencourt", "Paulistão Sub-15 · Clube Vital (C)", "Base", "Alta", "Felipe Salles", "Na fila", "sem IA no rosto"],
["sáb 08/08 11:00", "João Toscano", "Paulistão Sub-17 · São Bento (C)", "Base", "Alta", "Gui", "Na fila", "mesmo jogo do Leonan"],
["sáb 08/08 11:00", "Leonan", "Paulistão Sub-17 · São Bento (C)", "Especial · A", "Alta", "Cauã", "Na fila", "retorno de lesão"],
["sáb 08/08 11:00", "Arthur Diniz", "Paulistão Sub-17 · Nacional (C)", "Base", "Alta", "Letícia*", "Na fila", "⚠ marca ADIDAS (não Puma)"],
["sáb 08/08 11:00", "Tiago Barros", "Paulistão Sub-17 · Mauá (C)", "Base", "Alta", "Hyzzi", "Na fila", "jogo com Luiz Gusttavo e Cauã Rodrigues"],
["sáb 08/08 11:00", "Cauã Rodrigues", "Paulistão Sub-17 · Mauá (C)", "Base", "Alta", "(definir)", "Na fila", "compliance: envelope só após assinatura"],
["sáb 08/08 11:00", "Luiz Gusttavo", "Paulistão Sub-17 · Mauá (C)", "Base", "A confirmar", "Hyzzi", "Radar", "2º jogo do fds (S20 sexta) — confirmar com Fran"],
["sáb 08/08 15:00", "Luiz Felipe", "Gauchão Sub-15 · Progresso (C)", "Base", "Alta", "Hyzzi", "Na fila", ""],
["sáb 08/08 16:00", "Ryan Nascimento", "C. Nordeste Sub-20 · Liga de Miranda (F)", "Base", "Alta", "(definir)", "Na fila", ""],
["sáb 08/08 16:00", "Ferreira", "Brasileirão · Grêmio (F)", "Base", "Alta", "(definir)", "Na fila", "mesmo jogo do Pablo Maia"],
["sáb 08/08 16:00", "Pablo Maia", "Brasileirão · Grêmio (F)", "Base", "Alta", "(definir)", "Na fila", "mesmo jogo do Ferreira"],
["sáb 08/08 18:30", "Felipe Amaral", "Série B · Botafogo-SP (F)", "Base", "Alta", "(definir)", "Na fila", ""],
["dom 09/08 10:00", "Kayk Alboes", "Copa Paulista · Grêmio Prudente (C)", "Base", "Alta", "(definir)", "Na fila", ""],
["dom 09/08 15:30", "Thiaguinho", "Candangão Sub-20 · Santa Maria", "Base", "A confirmar", "Gui", "Radar", "⚠ evento diz Brasiliense — confirmar clube/empréstimo"],
["dom 09/08 18:30", "Gabigol", "Brasileirão · Athletico (C)", "Especial · A", "Alta", "Felipe Salles", "Na fila", "corrigido: Remo (Copa BR) foi 04/08"],
["ter 11/08 15:00", "Arthur Diniz", "Brasileirão Sub-17 · Santos (C)", "Base", "Alta", "Letícia*", "Na fila", "⚠ marca ADIDAS"],
["ter 11/08 19:30", "Thayllon", "Série B · Avaí × CRB (C)", "Especial · A", "Alta", "Felipe Salles", "Na fila", "4ComM + SPK"],
["ter 11/08 19:30", "Patrick de Lucca", "Série B · Avaí × CRB (F)", "Base", "A confirmar", "(definir)", "Radar", "mesmo jogo do Thayllon"],
["ter 11/08 21:30", "Ferreira", "Sul-Americana · Bolívar (F)", "Base", "Alta", "(definir)", "Na fila", "internacional — avaliar gatilho A"],
["ter 11/08 21:30", "Pablo Maia", "Sul-Americana · Bolívar (F)", "Base", "Alta", "(definir)", "Na fila", "internacional — avaliar gatilho A"],
["qui 13/08 19:00", "Gabigol", "Sul-Americana · Macará (C)", "Especial · A", "Alta", "Felipe Salles", "Na fila", "oitavas, ida"],
["sex 14/08 21:00", "Giovanni", "Superliga Kosovo · Prishtina (F)", "Base", "Alta", "Felipe Salles", "Na fila", ""],
["sáb 15/08 10:15", "Moisés", "Camp. Russo · Fakel Voronezh (C)", "Base", "Alta", "Felipe Salles", "Na fila", ""],
["sáb 15/08 15:00", "Ryan Nascimento", "C. Nordeste Sub-20 · Santa Cruz (C)", "Base", "Alta", "(definir)", "Na fila", ""],
["sáb 15/08 20:30", "Peglow", "MLS · CF Montréal (F)", "Especial · A", "Alta", "Edu/Leo", "Na fila", ""],
["sáb 15/08 21:00", "Ferreira", "Brasileirão · Coritiba (C)", "Base", "Alta", "(definir)", "Na fila", "mesmo jogo do Pablo Maia"],
["sáb 15/08 21:00", "Pablo Maia", "Brasileirão · Coritiba (C)", "Base", "Alta", "(definir)", "Na fila", "mesmo jogo do Ferreira"],
["dom 16/08 11:00", "Thayllon", "Série B · Operário (F)", "Base", "Alta", "Felipe Salles", "Na fila", ""],
["dom 16/08 18:30", "Felipe Amaral", "Série B · Athletic (C)", "Base", "Alta", "(definir)", "Na fila", ""],
["dom 16/08 18:30", "Patrick de Lucca", "Série B · Novorizontino (C)", "Base", "Alta", "(definir)", "Na fila", ""]
],

"rodizio": ["Aguirra*", "Brenelli", "Cauã Rodrigues", "Diego Fidelis", "Diogo Oliveira", "Felipe Amaral", "Felipe Oliveira", "Fellipe Lima", "Gustavo Defante", "Gustavo Passos", "Jean Louis", "João Toscano", "Karlos Samuel", "Kauê Canela", "Leonan ✓A", "Luca Canela", "Luigi", "Luiz Felipe", "Luiz Gusttavo", "Pablo Maia", "Patrick de Lucca", "Pedro Tizon", "Pietro Galli", "Rafa Martinez", "Rafinha Leonel", "Rosenthal", "Ryan Ridek", "Thalisson", "Thiaguinho", "Arthur Henrique", "Tiago Barros", "— já receberam no ciclo:", "Arthur Diniz (1)", "Enrico (1)", "Kayk (1)", "Ryan N. (1)", "Lorenzo (2)", "Moisés (2)", "Peglow (3)", "Giovanni (4)", "Thayllon (4)", "Gabigol (6)"],

"banco": [
["Karlos Samuel", "10/06", "Hyzzi", "vs Corinthians (cortado)", "story"],
["Luiz Gusttavo", "11/06", "Cauã", "vs Palmeiras (cortado)", "story"],
["Diego Fidelis", "13/06", "—", "jogo 13/06 (cortado)", "story"],
["Giovanni", "24/07", "F. Salles", "não foi ao jogo — 'guardar pro próximo'", "vídeo"]
],

"jogos": {
"Gabigol": [["Brasileirão", "Athletico", "Casa", "09/08", "18:30", "Vila Belmiro", "calendário PARTIDAS", "Alta", 0], ["Copa Sul-Americana", "Macará", "Casa", "13/08", "19:00", "Vila Belmiro", "calendário PARTIDAS — oitavas ida", "Alta", 1], ["Copa Sul-Americana", "Macará", "Fora", "20/08", "—", "—", "calendário PARTIDAS — oitavas volta", "Alta", 1]],
"Pablo Maia": [["Brasileirão", "Grêmio", "Fora", "08/08", "16:00", "Arena do Grêmio", "calendário PARTIDAS", "Alta", 0], ["Copa Sul-Americana", "Bolívar", "Fora", "11/08", "21:30", "Hernando Siles, La Paz", "calendário PARTIDAS", "Alta", 1], ["Brasileirão", "Coritiba", "Casa", "15/08", "21:00", "MorumBIS", "calendário PARTIDAS", "Alta", 0], ["Copa Sul-Americana", "Bolívar", "Casa", "18/08", "—", "MorumBIS", "calendário PARTIDAS", "Alta", 1]],
"Ferreira": [["Brasileirão", "Grêmio", "Fora", "08/08", "16:00", "Arena do Grêmio", "calendário PARTIDAS", "Alta", 0], ["Copa Sul-Americana", "Bolívar", "Fora", "11/08", "21:30", "Hernando Siles, La Paz", "calendário PARTIDAS", "Alta", 1], ["Brasileirão", "Coritiba", "Casa", "15/08", "21:00", "MorumBIS", "calendário PARTIDAS", "Alta", 0], ["Copa Sul-Americana", "Bolívar", "Casa", "18/08", "—", "MorumBIS", "calendário PARTIDAS", "Alta", 1]],
"Thayllon": [["Brasileirão Série B", "CRB", "Casa", "11/08", "19:30", "Ressacada", "calendário PARTIDAS · ⚠ jogo do Patrick tb", "Alta", 1], ["Brasileirão Série B", "Operário", "Fora", "16/08", "11:00", "Germano Krüger, Ponta Grossa", "calendário PARTIDAS", "Alta", 0]],
"Moisés": [["Campeonato Russo", "FK Rostov", "Fora", "08/08", "14:30", "Rostov Arena", "calendário PARTIDAS", "Alta", 0], ["Campeonato Russo", "Fakel Voronezh", "Casa", "15/08", "10:15", "VEB Arena", "calendário PARTIDAS", "Alta", 0], ["Copa da Rússia", "Akron Togliatti", "Casa", "18/08", "12:30", "—", "calendário PARTIDAS", "Alta", 1], ["Campeonato Russo", "Lokomotiv", "Casa", "22/08", "14:30", "VEB Arena", "calendário PARTIDAS", "Alta", 0], ["Campeonato Russo", "Akron Togliatti", "Fora", "28/08", "12:00", "—", "calendário PARTIDAS", "Alta", 0]],
"Peglow": [["MLS", "CF Montréal", "Fora", "15/08", "20:30", "Saputo Stadium", "calendário PARTIDAS", "Alta", 0], ["MLS", "New England Revolution", "Casa", "19/08", "20:30", "Audi Field", "calendário PARTIDAS", "Alta", 0], ["MLS", "Charlotte", "Fora", "22/08", "20:30", "—", "calendário PARTIDAS", "Alta", 0], ["MLS", "LAFC", "Casa", "29/08", "20:30", "Audi Field", "calendário PARTIDAS", "Alta", 0]],
"Giovanni": [["Superliga Kosovo", "Prishtina", "Fora", "14/08", "21:00", "Fadil Vokrri Stadium", "calendário PARTIDAS", "Alta", 0]],
"Antony": [["LaLiga", "Real Sociedad", "Casa", "21/08", "16:00", "La Cartuja, Sevilla", "calendário PARTIDAS", "Alta", 0], ["LaLiga", "Valencia", "Fora", "25/08", "16:00", "Mestalla", "calendário PARTIDAS", "Alta", 0], ["LaLiga", "Levante", "Fora", "29/08", "12:00", "Ciudad de Valencia", "calendário PARTIDAS", "Alta", 0]],
"Guilherme Torres": [["Stars League", "Al Ahli", "Casa", "22/08", "13:30", "—", "calendário PARTIDAS", "Alta", 0]],
"Palmberg": [["Primera Federación", "Hércules", "Fora", "29/08", "21:00", "—", "calendário PARTIDAS — data corrigida (era 30/07)", "Alta", 0]],
"Ryan Nascimento": [["Copa do Nordeste Sub-20", "Liga de Miranda", "Fora", "08/08", "16:00", "Arena Biran Castro, Cantanhede-MA", "calendário PARTIDAS", "Alta", 0], ["Copa do Nordeste Sub-20", "Santa Cruz", "Casa", "15/08", "15:00", "CT Evaristo de Macedo", "calendário PARTIDAS", "Alta", 0], ["Copa do Nordeste Sub-20", "Esporte", "Casa", "22/08", "15:00", "CT Evaristo de Macedo", "calendário PARTIDAS", "Alta", 0]],
"Patrick de Lucca": [["Brasileirão Série B", "Avaí", "Fora", "11/08", "19:30", "Ressacada", "calendário PARTIDAS · ⚠ mesmo jogo do Thayllon", "A confirmar", 0], ["Brasileirão Série B", "Novorizontino", "Casa", "16/08", "18:30", "Estádio Rei Pelé, Maceió", "calendário PARTIDAS", "Alta", 0]],
"Felipe Oliveira": [["—", "sem jogo mapeado", "—", "a definir", "—", "—", "preencher manual", "A confirmar", 0]],
"Kayk Alboes": [["Copa Paulista", "Grêmio Prudente", "Casa", "09/08", "10:00", "Gilberto Siqueira Lopes, Lins", "calendário PARTIDAS", "Alta", 0]],
"Felipe Amaral": [["Brasileirão Série B", "Botafogo-SP", "Fora", "08/08", "18:30", "Santa Cruz, Ribeirão Preto", "calendário PARTIDAS", "Alta", 0], ["Brasileirão Série B", "Athletic", "Casa", "16/08", "18:30", "Arena Independência", "calendário PARTIDAS", "Alta", 0]],
"Hwaskar": [],
"Thalisson": [["Brasileirão Série B", "Ponte Preta", "Casa", "07/08", "20:30", "Arena Castelão", "calendário PARTIDAS", "Alta", 0]],
"Luca Canela": [["BH Cup", "Grêmio", "Casa", "06/08", "15:00", "Toca da Raposa 1", "calendário PARTIDAS · com Gustavo Passos", "Alta", 0]],
"Gustavo Passos": [["BH Cup", "Grêmio", "Casa", "06/08", "15:00", "Toca da Raposa 1", "calendário PARTIDAS · com Luca Canela", "Alta", 0]],
"Karlos Samuel": [["Catarinense Sub-20", "rodada", "Casa", "15/08", "—", "Ressacada", "recorrência — confirmar", "A confirmar", 0]],
"Thiaguinho": [["Candangão Sub-20", "Santa Maria", "—", "09/08", "15:30", "Serejão, Taguatinga-DF", "calendário PARTIDAS · ⚠ evento diz Brasiliense — confirmar clube", "A confirmar", 0]],
"Lorenzo Dracena": [["Paulistão Sub-15", "Guarulhense", "Casa", "08/08", "09:00", "Academia de Futebol", "calendário PARTIDAS", "Alta", 0], ["Paulistão Sub-15", "rodada", "—", "sáb 15/08", "09:00", "a confirmar", "recorrência sáb 09h", "A confirmar", 0]],
"Enrico": [["Paulista Sub-14", "rodada", "—", "sáb/dom 15-16/08", "—", "a confirmar", "recorrência", "A confirmar", 0]],
"Luigi Dracena": [["IberCup/rodada", "a confirmar", "—", "a definir", "—", "—", "confirmar com Thiago", "A confirmar", 0]],
"Felipe Brenelli": [["Paulistão Sub-15", "São Bernardo FC", "Casa", "08/08", "09:00", "José Araújo Cintra, Amparo", "calendário PARTIDAS", "Alta", 0]],
"Rafa Martinez": [["Paulista Sub-14", "rodada", "—", "sáb/dom 15-16/08", "—", "a confirmar", "recorrência", "A confirmar", 0]],
"Ryan Ridek": [["Paulista Sub-14", "rodada", "—", "sáb/dom 15-16/08", "—", "a confirmar", "recorrência", "A confirmar", 0]],
"Aguirra": [["Paulistão Sub-17", "rodada", "—", "sáb 15/08", "11:00", "a confirmar", "recorrência sáb 11h", "A confirmar", 0]],
"Leonan": [["Paulistão Sub-17", "São Bento", "Casa", "08/08", "11:00", "Est. José Liberatti", "calendário PARTIDAS · com João Toscano", "Alta", 1]],
"Matheus Bittencourt": [["Paulistão Sub-15", "Clube Vital", "Casa", "08/08", "09:00", "Hermínio Espósito", "calendário PARTIDAS", "Alta", 0]],
"Tiago Barros": [["Paulistão Sub-17", "Mauá", "Casa", "08/08", "11:00", "CT Rei Pelé", "calendário PARTIDAS · com Luiz Gusttavo e Cauã Rodrigues", "Alta", 0]],
"Luiz Gusttavo": [["Paulistão Sub-20", "São Bento", "Casa", "07/08", "15:00", "CT Rei Pelé", "calendário PARTIDAS", "Média", 0], ["Paulistão Sub-17", "Mauá", "Casa", "08/08", "11:00", "CT Rei Pelé", "calendário PARTIDAS · 2º jogo do fds — confirmar", "A confirmar", 0]],
"Cauã Rodrigues": [["Paulistão Sub-17", "Mauá", "Casa", "08/08", "11:00", "CT Rei Pelé", "calendário PARTIDAS · com Tiago Barros e Luiz Gusttavo", "Alta", 0]],
"Diogo Oliveira": [["Paulistão Sub-15", "rodada", "—", "sáb 15/08", "09:00", "a confirmar", "recorrência sáb 09h", "A confirmar", 0]],
"Luiz Felipe": [["Gauchão Sub-15", "Progresso", "Casa", "08/08", "15:00", "CT do Juventude, Caxias do Sul", "calendário PARTIDAS", "Alta", 0]],
"Pietro Galli": [["Mineiro Sub-15", "Betim", "Casa", "08/08", "08:00", "Toca da Raposa 1", "calendário PARTIDAS — CONFIRMADO", "Alta", 0]],
"Rafinha Leonel": [["Sub-20", "rodada", "—", "fds 15-16/08", "—", "a confirmar", "recorrência", "A confirmar", 0]],
"Rosenthal": [["Paulistão Sub-17", "rodada", "—", "sáb 15/08", "11:00", "a confirmar", "recorrência sáb 11h", "A confirmar", 0]],
"João Toscano": [["Paulistão Sub-17", "São Bento", "Casa", "08/08", "11:00", "Est. José Liberatti", "calendário PARTIDAS · com Leonan", "Alta", 0]],
"Arthur Diniz": [["Paulistão Sub-17", "Nacional", "Casa", "08/08", "11:00", "CPD Red Bull Bragantino", "calendário PARTIDAS", "Alta", 0], ["Brasileirão Sub-17", "Santos", "Casa", "11/08", "15:00", "CPD Red Bull Bragantino", "calendário PARTIDAS", "Alta", 0], ["Brasileirão Sub-17", "Bahia", "Fora", "18/08", "15:00", "CT Evaristo de Macedo", "calendário PARTIDAS", "Alta", 0]],
"Arthur Henrique": [["Paulistão Sub-15", "São Bento", "Casa", "08/08", "09:00", "Est. José Liberatti", "calendário PARTIDAS · com Dieguinho", "Alta", 0]],
"Diego Fidelis": [["Paulistão Sub-15", "São Bento", "Casa", "08/08", "09:00", "Est. José Liberatti", "calendário PARTIDAS · com Thuy", "Alta", 0]],
"Gustavo Defante": [["Paulista Sub-17", "—", "—", "08/08", "—", "—", "aviso 03/08: preservado (amarelo)", "Baixa", 0]],
"Fellipe Lima": [["Paulistão Sub-15", "EC São Bernardo", "Casa", "08/08", "09:00", "—", "calendário PARTIDAS", "Alta", 0]],
"Pedro Tizon": [["Paulista Sub-13", "rodada", "—", "dom 16/08", "09:00", "a confirmar", "recorrência", "A confirmar", 0]],
"Jean Louis": [["Championnat U19", "rodada", "—", "a definir", "—", "—", "confirmar com Ivanildo", "A confirmar", 0]],
"Kauê Canela": [["—", "sem jogo mapeado", "—", "a definir", "—", "—", "preencher manual", "A confirmar", 0]]
}
};
